### ISSUE TITLE
Saving sound data still broken

### ISSUE THREAD

**Issue by AndreiArdei** [levietduc/Environmental-Sound-Classification#1]
Phone used : Google Pixel 3a
Android version : 12.0
App version: The one uploaded on 13.12.2021 @ 11:22AM

Issue: When collecting data, the app does not write values to the file created. I can find my SoundData folder using Device File Explorer in Android Studio. However, all files within the SoundData folder have a size of 44B and are actually empty files. 
Trying to open them with Audacity or VLC results in a file with not even a second of recording (even though I let it run for 4 min)

![image](https://user-images.githubusercontent.com/57090617/145823105-cd43559d-9d91-4338-aa68-229da9b1f1f1.png)

@levietduc  @vinhtqc  could you have a look into that ?

**Comment by vinhtqc** [comment]
I am looking into that. Found this happens on a device different to what I tested. I will figure out it now and reply you later.

**Comment by vinhtqc** [comment]
> Phone used : Google Pixel 3a Android version : 12.0 App version: The one uploaded on 13.12.2021 @ 11:22AM
> 
> Issue: When collecting data, the app does not write values to the file created. I can find my SoundData folder using Device File Explorer in Android Studio. However, all files within the SoundData folder have a size of 44B and are actually empty files. Trying to open them with Audacity or VLC results in a file with not even a second of recording (even though I let it run for 4 min)
> 
> ![image](https://user-images.githubusercontent.com/57090617/145823105-cd43559d-9d91-4338-aa68-229da9b1f1f1.png)
> 
> @levietduc @vinhtqc could you have a look into that ?

**Comment by vinhtqc** [comment]
AndreiArdei: I have updated the new program to fix this issue. Please download it and try again.

**Comment by AndreiArdei** [comment]
Yes. I can confirm, this fixes it. Thanks !


În lun., 13 dec. 2021 la 16:22, vinhtqc ***@***.***> a scris:
